spring.datasource.url=jdbc:postgresql://localhost:5432/app?currentSchema=desafiobackendtest
spring.datasource.username=postgres
spring.datasource.password=76872985
spring.datasource.driver-class-name=org.postgresql.Driver